const DATA = [
    {
      "Timestamp": "2018/10/30 2:17:21 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "20 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ik verlucht de kamers 's ochtends.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:21:04 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 75,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "verluchten, vochtige lucht voorkomen",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:37:02 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 17,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:37:15 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 40,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 2:37:31 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "40 jaar?",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "raam openzwieren",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:38:08 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "25 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen vaak open zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:38:13 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "20 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "verluchten, potjes met water op de verwarming zetten voor vochtigheid",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:39:08 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 30,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "90 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten dagelijks",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:40:37 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:41:50 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 83,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "We verluchten en controleren vaak de vochtigheid",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:42:28 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "oud",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "plantjes, raampje open enz",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:42:57 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 30,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "DE RAMEN OPENZETTEN",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:43:42 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 30,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig het raam open zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:43:49 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:44:03 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Plantjes voor de zuurstof",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 2:44:10 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "25j",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:44:21 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 40,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:44:28 PM GMT+1",
      "Wat is uw geslacht?": "Zeg ik liever niet",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "ja toch een goei 30 jaar denk ik toch",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:44:59 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ventilatie, ramen open zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:45:47 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:46:14 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "30 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:46:20 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "60 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen openzetten, potjes met water laten verdampen,...",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:46:32 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 8,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:46:59 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 2:47:11 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 17,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:47:24 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "25 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchtinig",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:47:34 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 8,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ventilatie",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:48:51 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "2 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Slapen met het raam open, overdag soms het raam open laten staan",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:49:02 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 15,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:52:04 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Water op de kachel voor de vochtigheid, CO melder en luchtbevochtiger",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:52:09 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 100,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:52:16 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "regelmatig een raam openzetten, en met het raam open slapen",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:52:41 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 44,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "75 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen en deuren af en toe openzeten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:53:33 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 25,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:54:42 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 12,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ruiten open, deuren open na het douchen, Niet verwarmen tot het echt koud wordt",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:55:24 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "Zeker 40 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Af en toe de ramen open zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:55:30 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 2:56:17 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 2:58:10 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "70 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:01:01 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "100 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:01:40 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "/",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:05:48 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 30,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten door ramen en deuren open te zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:06:11 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 16,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "7 jaar ofzo",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Rookmelders",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:07:13 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:08:55 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 68,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Andere",
      "Hoe oud is uw woning?": 200,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Scheetjes",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 3:10:26 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 18,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "ramen openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:10:54 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "60 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:12:45 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "20 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:12:55 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 25,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ventilatie",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:25:04 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "22 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:30:33 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 24,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "18 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:30:34 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "15 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "ramen open zetten, snachts deuren open laten staan (binnendeuren enkel),",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:32:08 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 100,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:32:13 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "10jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Af en toe ruiten open, luchtbevochtiger",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:33:02 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "15 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:33:40 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Andere",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:33:54 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 103,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:37:39 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "nieuwbouw 2018",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen vaak openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:37:47 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "7 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig ramen en deuren open",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:37:52 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "30 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:39:07 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:43:33 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "ramen elke dag open, co2 melder",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:47:46 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 40,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Co melders",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:51:46 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "1 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ventilatiesysteem",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:54:32 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 35,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 3:57:10 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Raam open, vochtigheid vermijden",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 3:59:55 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 1895,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Geregeld ramen en deuren openzetten, Netatmo 'weerstations'",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:00:01 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 65,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "35 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Goed verluchten 's morgens",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:01:12 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:04:04 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "50 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig mijn ramen open zetten om te verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:08:34 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 32,
      "Wat is uw woonsituatie?": "Ik woon samen met anderen (kamergenoten, vrienden, ...)",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "100 Jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:13:23 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Zuinigere toestellen gebruiken met weinig uitstoot",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:21:02 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "40 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Vochtigheidsmachine",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:23:39 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 17,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Andere",
      "Hoe oud is uw woning?": "3 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:26:45 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 15,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Elke dag verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:30:37 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "+-18 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:31:13 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "20 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "regelmatig verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:31:23 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 30,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:36:46 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "50 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen voldoende openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:38:37 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 120,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Co melders, voldoende verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:46:51 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "17 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 4:48:45 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 60,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "30 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Dagelijks goed verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:49:52 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 17,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "Geen idee",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:50:42 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ventilatie",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:55:53 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 28,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:56:01 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 18,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen open",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 4:56:20 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 22,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Kamers verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 4:57:55 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "120 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Raam af en toe open zetten, dampkap aanzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:01:54 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 59,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "33 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 5:02:17 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "6 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig luchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:07:12 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "20 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:15:32 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 40,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen vaak open zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:17:12 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 35,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Veel verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:18:02 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 68,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ventileren",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:20:22 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 50,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 21,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:21:59 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Andere",
      "Hoe oud is uw woning?": "6 jaar denk ik",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ik zet bijna elke dag mijn raam open en op kot staat mijn verluchtingsklepje altijd open",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 5:26:41 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "15 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Voldoende en regelmatig verluchten door ramen en deuren open te zetten wanneer de buitentemperatuur dat toelaat.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:27:23 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 70,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Elke dag de kamers verluchten en als de verwarming aan staat een luchtvochtiger zetten.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:27:25 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 17,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 200,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:38:34 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon samen met anderen (kamergenoten, vrienden, ...)",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": 30,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 5:40:09 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 22,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen openzetten overdag.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:40:52 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 50,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 65,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Re. En deuren dagelijks openzetten.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 5:47:26 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 52,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 21,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen openzetten. Luchtbevochtigers aan verwarming hangen.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 5:48:37 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "2jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ik probeer er op te letten om mijn kamer voldoende te verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 5:55:45 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "3 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 5:56:21 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "7 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen open enzo die dingen",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 5:57:29 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "Zeker 60 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 5:59:35 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 25,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig ramen openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 6:00:25 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Op de vensterbank binnen staan bakken die het vocht opnemen uit slaapkamers. Dagelijks staat de ruit wel eens open voor te verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 6:03:36 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 25,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Voldoende de slaapkamer verluchten.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 6:04:56 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 67,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 84,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Raam enige tijd openen",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 6:06:35 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 21,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 6:08:02 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 75,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig raam openzetten om te verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 6:09:48 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "20-30 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 6:46:58 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "50 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "veel verluchten, planten houden, niet binnen roken",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 6:56:37 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon samen met anderen (kamergenoten, vrienden, ...)",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": 42,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 7:01:01 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 22,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 7:07:21 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "25 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 7:08:17 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "23 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Dagelijks meerdere uren de ramen openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 7:44:17 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "50 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 7:59:26 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": 10,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 8:04:41 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "40 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 8:21:25 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": 75,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "ja",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/30 8:25:44 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "20 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Kamers goed verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 8:39:21 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 16,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 8:43:37 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "10 jaar (ruwe schatting)",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "ontvochtiger in badkamer",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 8:47:13 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "18 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Raam open, ventilator, dampkap open",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 8:52:03 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 48,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 61,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "wettelijk verplicht ventilatie systeem",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 9:03:27 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "eind 1800",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "ramen openzetten, roosters aan de ramen",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 9:14:14 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 24,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "Van april 2018",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 9:30:45 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 9:32:06 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 10:45:07 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 50,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 10:47:28 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Andere",
      "Hoe oud is uw woning?": "40 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/30 11:11:18 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen af en toe openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/30 11:33:00 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "40 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen regelmatig open laten, vochtige ruimtes open laten, ...",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/31 7:45:02 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "Geen idee",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/31 7:59:57 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ramen open zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/31 9:42:02 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "23 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/31 10:44:01 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon alleen of met een partner",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "70jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ik verlucht elke dag, maar woon in een stadscentrum (slechte luchtkwaliteit)",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/10/31 10:52:59 AM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "+-6j",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Door het raam open te zetten.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/31 11:15:40 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "100jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/31 11:38:29 AM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "12 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/31 2:12:17 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "50 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Dagelijks alle ramen even openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/31 3:23:06 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 25,
      "Wat is uw woonsituatie?": "Ik woon samen met anderen (kamergenoten, vrienden, ...)",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "50 jaar?",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Vooral door regelmatig voor goede verluchting te zorgen. Ramen openen, regelmatig schoonmaken, vochtplekken in de mate van het mogelijke aanpakken",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/10/31 5:41:48 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 20,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Voldoende verluchting",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/10/31 11:05:38 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "10 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/01 9:00:57 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 56,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 30,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Regelmatig deuren openzetten, verluchtingsroosters in vensters open",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/01 9:26:41 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 24,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "30 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Ik zet mijn raar iedere dag open voor een goeie 20 minuten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/11/01 9:30:26 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 100,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Elke dag ramen open zetten.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/11/01 9:38:04 AM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "± 50",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Raam openzetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/11/01 10:59:03 AM GMT+1",
      "Wat is uw geslacht?": "Zeg ik liever niet",
      "Wat is uw leeftijd?": 22,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": "23 jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/11/01 5:42:47 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 18,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "+-50jaar",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Veel verluchten door het raam open te zetten",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/02 1:01:15 PM GMT+1",
      "Wat is uw geslacht?": "Man",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": 80,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/03 12:09:53 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Alleenstaand huis",
      "Hoe oud is uw woning?": 25,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Verluchting, elke dag de ramen openen",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/03 2:52:45 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 23,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Appartement",
      "Hoe oud is uw woning?": "20j",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Soms zet ik de deur eens open om te verluchten. Ik laat de chauffage altijd zacht aanstaan om schimmel te voorkomen.",
      "Denkt u dat de lucht bij u in huis gezond is?": "Nee"
    },
    {
      "Timestamp": "2018/11/04 3:02:14 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik woon bij mijn ouders",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": "45j",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "zorgen dat ramen af en toe worden opengezet als verluchting",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/11/04 5:55:30 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 19,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": "Geen idee aangezien ik op kot zit",
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/05 10:56:51 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 20,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Halfopen bebouwing",
      "Hoe oud is uw woning?": 10,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Volledige dat kamers verluchten, letten op vochtvlekken, vochtvreters",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ja"
    },
    {
      "Timestamp": "2018/11/06 6:38:52 PM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 21,
      "Wat is uw woonsituatie?": "Ik zit op kot",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 60,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Nee",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    },
    {
      "Timestamp": "2018/11/07 8:57:45 AM GMT+1",
      "Wat is uw geslacht?": "Vrouw",
      "Wat is uw leeftijd?": 32,
      "Wat is uw woonsituatie?": "Ik woon samen met mijn gezin",
      "In wat voor woning leeft u?": "Rijhuis",
      "Hoe oud is uw woning?": 87,
      "Bent u bewust bezig met de luchtkwaliteit in uw woning? (verlucht u, let u op vochtigheid, heeft u CO melders, ... ?)": "Ja",
      "Hoe zorgt u voor betere luchtkwaliteit binnenshuis?": "Dagelijks alle ruimtes verluchten en ventilatie in elke ruimte",
      "Denkt u dat de lucht bij u in huis gezond is?": "Ik weet het niet"
    }
  ]